// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/blog/new": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/equipment": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/blog/new" | "/members" | "/equipment" | "/calendar" | "/*";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/dashboard" | "/blog/new" | "/members" | "/equipment" | "/calendar";
  };
  "./routes/_auth.dashboard.tsx": {
    id: "routes/_auth.dashboard";
    page: "/dashboard";
  };
  "./routes/_auth.blog.new.tsx": {
    id: "routes/_auth.blog.new";
    page: "/blog/new";
  };
  "./routes/_auth.members.tsx": {
    id: "routes/_auth.members";
    page: "/members";
  };
  "./routes/_auth.equipment.tsx": {
    id: "routes/_auth.equipment";
    page: "/equipment";
  };
  "./routes/_auth.calendar.tsx": {
    id: "routes/_auth.calendar";
    page: "/calendar";
  };
  "./routes/catchall.tsx": {
    id: "routes/catchall";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/register": typeof import("./app/./routes/register.tsx");
  "routes/_auth": typeof import("./app/./routes/_auth.tsx");
  "routes/_auth.dashboard": typeof import("./app/./routes/_auth.dashboard.tsx");
  "routes/_auth.blog.new": typeof import("./app/./routes/_auth.blog.new.tsx");
  "routes/_auth.members": typeof import("./app/./routes/_auth.members.tsx");
  "routes/_auth.equipment": typeof import("./app/./routes/_auth.equipment.tsx");
  "routes/_auth.calendar": typeof import("./app/./routes/_auth.calendar.tsx");
  "routes/catchall": typeof import("./app/./routes/catchall.tsx");
};